Repository Icinga/icinga-testing, pull requests merged in 2022-05, with the labels that each got.

#22 Allow to set additional raw Icinga DB YAML config
  internal/services/icingadb/docker_binary.go
  internal/services/icingadb/icingadb.go
  it.go
  services/icingadb.go
  services/icingadb.yml
Labels: enhancement, cla/signed

#21 Improve compatibility for different database versions
  go.mod
  go.sum
  internal/services/mysql/docker.go
  internal/services/mysql/root_connection.go
  internal/services/postgresql/docker.go
  internal/services/postgresql/root_connection.go
  services/mysql.go
  services/postgresql.go
Labels: cla/signed

#23 Add Go package docs including description of environment variables
  it.go
Labels: documentation, cla/signed

#11 Write all Redis command to the debug log
  internal/services/redis/docker.go
  it.go
Labels: cla/signed

#24 Split Redis address into host and port
  services/icingadb.yml
Labels: cla/signed
